// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7oTqM32Gvm5dpnjkesUrUEBJ6CMorWn8',
    appId: '1:756568610379:web:f4fb4365f798a0f878dfce',
    messagingSenderId: '756568610379',
    projectId: 'calmcup-24f38',
    authDomain: 'calmcup-24f38.firebaseapp.com',
    databaseURL: 'https://calmcup-24f38-default-rtdb.firebaseio.com',
    storageBucket: 'calmcup-24f38.firebasestorage.app',
    measurementId: 'G-H6C2QF80WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6azdipSi3_9DujUFook-mPhkQiJmdZ5A',
    appId: '1:756568610379:android:0abf9e58520d5ba578dfce',
    messagingSenderId: '756568610379',
    projectId: 'calmcup-24f38',
    databaseURL: 'https://calmcup-24f38-default-rtdb.firebaseio.com',
    storageBucket: 'calmcup-24f38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPn2BUh39_4RqPL8QlAh7q2DXnRvftt4',
    appId: '1:756568610379:ios:4348b398f833595578dfce',
    messagingSenderId: '756568610379',
    projectId: 'calmcup-24f38',
    databaseURL: 'https://calmcup-24f38-default-rtdb.firebaseio.com',
    storageBucket: 'calmcup-24f38.firebasestorage.app',
    iosBundleId: 'com.example.atv4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPn2BUh39_4RqPL8QlAh7q2DXnRvftt4',
    appId: '1:756568610379:ios:4348b398f833595578dfce',
    messagingSenderId: '756568610379',
    projectId: 'calmcup-24f38',
    databaseURL: 'https://calmcup-24f38-default-rtdb.firebaseio.com',
    storageBucket: 'calmcup-24f38.firebasestorage.app',
    iosBundleId: 'com.example.atv4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7oTqM32Gvm5dpnjkesUrUEBJ6CMorWn8',
    appId: '1:756568610379:web:bc639fe0f38f387678dfce',
    messagingSenderId: '756568610379',
    projectId: 'calmcup-24f38',
    authDomain: 'calmcup-24f38.firebaseapp.com',
    databaseURL: 'https://calmcup-24f38-default-rtdb.firebaseio.com',
    storageBucket: 'calmcup-24f38.firebasestorage.app',
    measurementId: 'G-JRWNESXQWX',
  );
}
